# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type static --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type static --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3 --tss_statistical_penalty 4
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type static --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type blend --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type blend --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type blend --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type dba --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type dba --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type dba --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type dark --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type dark --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4
# python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type dark --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3
python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type 3dfed --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5
python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type 3dfed --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4
python main_parallel.py --config ./conf/rb_mnist_lenetsm_static_dirichlet.yaml --attack_type 3dfed --tss_statistical_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3