# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type static --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type static --tss_hard_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3 --tss_statistical_penalty 4 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type static --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type blend --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type blend --tss_hard_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type blend --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type dba --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type dba --tss_hard_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type dba --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type dark --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type dark --tss_hard_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
# python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type dark --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type 3dfed --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type 3dfed --tss_hard_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type 3dfed --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type invisible --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 20 --tss_hard_k 2  --tss_statistical_penalty 5 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type invisible --tss_hard_reject 1 --tss_layer_count 10 --portion 0.15 --num_users 20 --tss_hard_k 3  --tss_statistical_penalty 4 --tss_metamask 1 --tss_important_percentile 50 --epochs 50
python main_parallel.py --config ./conf/rb_100_resnet20sm_static_dirichlet.yaml --attack_type invisible --tss_hard_reject 1 --tss_layer_count 10 --portion 0.1 --num_users 40 --tss_hard_k 4  --tss_statistical_penalty 3 --tss_metamask 1 --tss_important_percentile 50 --epochs 50